"""
Simple usage examples for refined MilvusHelper
"""
from .milvus_helper import MilvusHelper


def example_basic_usage():
    """Basic usage example"""
    print("=== Example 1: Basic Usage ===\n")
    
    # Initialize from YAML config
    helper = MilvusHelper("config.yaml")
    
    # List collections (already created from config)
    collections = helper.list_collections()
    print(f"Collections: {collections}\n")
    
    # Insert data
    data = [
        {
            "id": "doc_001",
            "embedding": [0.1] * 768
        },
        {
            "id": "doc_002", 
            "embedding": [0.2] * 768
        },
        {
            "id": "doc_003",
            "embedding": [0.3] * 768
        }
    ]
    
    result = helper.insert("my_collection", data)
    print(f"Insert result: {result}\n")
    
    # Search
    query_vector = [0.15] * 768
    results = helper.search(
        collection_name="my_collection",
        query_vectors=[query_vector],
        anns_field="embedding",
        limit=5,
        output_fields=["id", "distance"]
    )
    
    print(f"Search results: {results}\n")


def example_json_config():
    """Use JSON configuration"""
    print("=== Example 2: Using JSON Config ===\n")
    
    # Initialize from JSON config
    helper = MilvusHelper("config.json")
    
    collections = helper.list_collections()
    print(f"Collections from JSON: {collections}\n")


def example_query_filter():
    """Query with filter"""
    print("=== Example 3: Query with Filter ===\n")
    
    helper = MilvusHelper("config.yaml")
    
    # Query specific documents
    results = helper.query(
        collection_name="my_collection",
        filter_expr='id in ["doc_001", "doc_002"]',
        output_fields=["id"]
    )
    
    print(f"Query results: {results}\n")


def example_advanced_config():
    """Advanced configuration with multiple collections"""
    print("=== Example 4: Advanced Config ===\n")
    
    # Load advanced config with multiple collections
    helper = MilvusHelper("config_advanced.yaml")
    
    # List all collections
    collections = helper.list_collections()
    print(f"All collections: {collections}\n")
    
    # Get stats for each collection
    for col in collections:
        stats = helper.get_collection_stats(col)
        print(f"Stats for {col}: {stats}\n")
    
    # Insert into documents collection
    doc_data = {
        "id": "doc_001",
        "content": "Machine learning is a subset of artificial intelligence",
        "dense_vector": [0.1] * 1024
        # sparse_vector will be auto-generated by BM25 function
    }
    
    helper.insert("documents", doc_data)
    print("Document inserted\n")
    
    # Insert into products collection
    product_data = {
        "product_id": "prod_001",
        "title": "Wireless Headphones",
        "price": 99.99,
        "in_stock": True,
        "title_embedding": [0.2] * 768
    }
    
    helper.insert("products", product_data)
    print("Product inserted\n")


def example_batch_operations():
    """Batch insert and search"""
    print("=== Example 5: Batch Operations ===\n")
    
    helper = MilvusHelper("config.yaml")
    
    # Batch insert
    batch_data = [
        {"id": f"batch_{i:03d}", "embedding": [0.1 * i] * 768}
        for i in range(100)
    ]
    
    helper.insert("my_collection", batch_data)
    print(f"Inserted {len(batch_data)} records\n")
    
    # Get collection stats
    stats = helper.get_collection_stats("my_collection")
    print(f"Collection stats: {stats}\n")


def example_delete_operations():
    """Delete operations"""
    print("=== Example 6: Delete Operations ===\n")
    
    helper = MilvusHelper("config.yaml")
    
    # Delete specific documents
    helper.delete(
        collection_name="my_collection",
        filter_expr='id == "doc_001"'
    )
    print("Deleted doc_001\n")
    
    # Delete by range
    helper.delete(
        collection_name="my_collection",
        filter_expr='id like "batch_%"'
    )
    print("Deleted batch documents\n")


if __name__ == "__main__":
    try:
        example_basic_usage()
        # example_json_config()
        # example_query_filter()
        # example_advanced_config()
        # example_batch_operations()
        # example_delete_operations()
        
    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()