# Penulis blog. Kunci "kurnia" dipakai di bagian authors setiap tulisan.
authors:
  kurnia:
    name: Kurnia Zulda Matondang
    description: Penulis Zul
    avatar: https://github.com/kazuma313.png
    url: https://github.com/kazuma313
